name: PR Review Commenter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review-pr:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR diff
        id: pr_diff
        run: |
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          gh pr diff "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Python review script
        id: review_api
        run: python3 scripts/review_pr.py
        env:
          DIFF: ${{ steps.pr_diff.outputs.diff }}
          RUNPOD_TOKEN: ${{ secrets.RUNPOD_TOKEN }}

      - name: Post comment on PR
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" \
            --body "${{ steps.review_api.outputs.comment }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
